### ISSUE TITLE
No search box on Tampermonkey Dolphin

### ISSUE THREAD

**Issue by Slofe** [bewam/userscripts#1]
Hey,

Seems fetlife have updated so your script isn't working now. I'm sure you were expecting this but just thought I'd let you know.

**Comment by bewam** [comment]
I can make a branch for legacy javascript like the old version of the script. The version works on desktops, as far as I know. Fetlife devs just actually changed the HTML class names. I'm not able to find actually a non time eating solution.

**Comment by Slofe** [comment]
Hi, did you find a fix for this? I just tried the 229 version of the script and the newest one and neither of them run on Tampermonkey Dolphin now.

**Comment by Slofe** [comment]
Hi, did you find a fix for this? I just tried the 229 version of the script and the newest one and neither of them run on Tampermonkey Dolphin now.

**Comment by Slofe** [comment]
Hi, did you find a fix for this? I just tried the 229 version of the script and the newest one and neither of them run on Tampermonkey Dolphin now.

**Comment by Slofe** [comment]
Hi, did you find a fix for this? I just tried the 229 version of the script and the newest one and neither of them run on Tampermonkey Dolphin now.

**Comment by bewam** [comment]
As always, [the brand new old es5 version](https://github.com/bewam/userscripts/blob/es5/fetlife_filter_members/fetlife_filter_members_ASL-name-role-status-avatar_.user.js) may be functional.
I worked on an automaton to easily build it. So the es5 branch should follow the master one whenever script changes.

**Comment by Slofe** [comment]
Sorry, I didn't see this old version before.  It works in the sense a box is showing again and I can choose different parameters but it doesn't find any members. It just says showingn 0 of 0.

**Comment by bewam** [comment]
My bad, It was new.
Really bad, I spend so much time just for this.
Can't you really use a PC with chrome/firefox ? Can't you help me with a debug log (connect adb), logcat, send the log.
It's not a beer I'll ask, it's a salary.

**Comment by Slofe** [comment]
I don't have a PC anymore and I'm not about to buy another one just so I can make searching for women on fetlife a bit easier! I would certainly use greasemonkey if I did.  I'd be more than happy to help you with debugging but I have no idea about scripting at all.  If you can explain how to create a log of your script running on my machine or point me in the direction of instructions on how to do it then sure, no problem I'm happy to help.

Once again I do really appreciate all your help.

**Comment by bewam** [comment]
If you don't mind using firefox(fennec) for android. I have a solution for running fetlife_all_members on it. I got it work on that system, that's good news.
I installed an extension called [USI (User|Unified Script Injector)](https://addons.mozilla.org/fr/android/addon/userunified-script-injector/) which is fairly new, one year. I adapt a bit for it, it would work, even if  USI is in beta.

**Comment by Slofe** [comment]
I tried it with firefox and that addon but still no luck this end.  Unless I'm doing something wrong of course but the addon says the script is loaded and added but no box loads.

**Comment by bewam** [comment]
I use its 0.3.0-a-alpha version.
https://addons.mozilla.org/fr/android/addon/userunified-script-injector/versions/

**Comment by Slofe** [comment]
Thanks, I'll wait for you to fix it. I did try and replace the line but didn't seemn to work. I probably did it wrong! I'm using the es5 version.

**Comment by bewam** [comment]
You'd better use the one on master branch, it works with the modification line 10.

**Comment by Slofe** [comment]
Boo Yeah! It's working now with the master script and it's faster than it is in tampermonkey, nice one thank you :)

**Comment by bewam** [comment]
Happy filtering !
